### ISSUE TITLE
QMK keyboard firmware

### ISSUE THREAD

**Issue by kilokeith** [TweetyDaBird/Little-Big-Scroll#3]
Hi, I've putting together a Little Big Scroll 4, but I'm stuck at the programming step. What keyboard should I tell QMK that I'm flashing?
I do se the .hex file in this project, and I can flash that... but then what? Where should I start with putting together a layout?

Thanks! This is a nice project.

**Comment by TweetyDaBird** [comment]
Thanks for the praise, but unfortunately you will get a slightly testy reply back, as this is a clear issue of not reading, not the instructions being unclear in any way. I will however update them to be overly obvious from now on, as this seems to be a common issue.

Why do people insist on trying to 'tell QMK what keyboard they are flashing'? The label on that drop box clearly states "Keyboard from qmk.fm" meaning it will download the firmware for the keyboard you select from that database. And obviously if the keyboard is not in that database, you cannot download it from there. 

The dropdown has nothing to do with what keyboard you are flashing, but with what file you want to download. If you were in fact using QMK and building your own layout as you allude to, selecting a firmware from here would flash the default firmware with the default layout as downloaded, not your own layout.

The supplied .HEX file is for VIAL-QMK. Download the software [here](https://get.vial.today) and then you have all the options to dynamically assign keys, just like VIA does, only open source. The firmware supports RGB as backlight, not a matrix, since 2*3 is a bit limiting anyways.

If you very much prefer to use QMK without VIAL, you will either have to build the firmware on your own from the files supplied in the QMK git under my username, or wait until its in the QMK main git.

**Comment by Brittle73** [comment]
Seconding this...

Got ghosted by you on Tindie after weeks of discussion over this. Let's not be "testy" with people who are nicely and justifiably requesting support on an open source platform like OP here. Their request was overwhelmingly positive and reasonable. QMK _is_ open source and the provided firmware for VIAL does not perform all of the functionality advertised with the product. They just asked for assistance with the product you sold them.

**Comment by TweetyDaBird** [comment]
> Seconding this...
> 
> 
> 
> Got ghosted by you on Tindie after weeks of discussion over this. Let's not be "testy" with people who are nicely and justifiably requesting support on an open source platform like OP here. Their request was overwhelmingly positive and reasonable. QMK _is_ open source and the provided firmware for VIAL does not perform all of the functionality advertised with the product. They just asked for assistance with the product you sold them.


Sorry you feel that way. I have been working on the firmware the last week or so every free night, and it should be ready to be published in a nights work or two, giving you all a base to work from. 

The 'ghosting' is probably more part of me leaving tindie altogether since they refuse to do anything to support EU tax rules, or any form of shipping calculations, meaning I was making losses on all shipping. Right now the shop there is sort of deactivated and about to time out.

**Comment by TweetyDaBird** [comment]
LSB 4 & LSB 6 is now in main QMK repo, so should be less confusing.

* Note that using QMK online Configurator still isn't a great idea, since the main feature, ie the encoder won't work in that case.
