### ISSUE TITLE
Where's the open source firmware?

### ISSUE THREAD

**Issue by Brittle73** [TweetyDaBird/Little-Big-Scroll#4]
We spent weeks in chat on the purchasing platform until you ghosted and left the product pages now notated with a negative jab at someone from Tindie, and still no open source code. You don't necessarily have to _support_ this I suppose, but the product was advertised with full QMK support and the only file on this Git is the Hex file for VIAL. Which does not support all of the functionality advertised in the product and cannot really be reverse engineered to get back to true source.

I see multiple people have asked you for this with interesting results. Will you provide source firmware for your open source, QMK product?

Thanks.

**Comment by TweetyDaBird** [comment]
Well, since you are now the one making jabs, let's take this public in the most appropriate way. 

Your behavior of asking the same thing in three different places is non-constructive, and quite frankly trolling, nothing else. I have deleted the other comments and replaying here instead, as I will then close this issue. 

This is not the correct forum for your question. Your question is not an 'issue' but belongs in a discussion.

An issue in this case would be with the hardware, which is what this Git is regards too. If it should be an issue it should be in the Git for the firmware. A discussion however would be the correct place to continue the conversation we had on Tindie, which I'm more than happy too. 

As for me leaving Tindie, that was because they absolutely refuse to support any kind of shipping calculations, making the shipping a loss in most cases as it never matched the shipping providers fees and was at best a guessing game. Add no support for EU tax regulations and a few other big issues in development and it was impossible to stay. As for the jab, I'll gladly discuss that in private. 

Unfortunately deactivating the store also deactivated any email notifications even though the store remains in place until the request to deactivated it times out. I obviously didn't anticipate that, so there was no intention to ghost you. 

As for the firmware, give me a few more nights, and you will all have a QMK base to work from. It takes a bit more time than I'd like when juggling kids, work etc.
